---
- name: Setup Jenkins on EC2
  hosts: jenkins
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install Java
      yum:
        name: java-11-amazon-corretto
        state: present

    - name: Remove existing Jenkins repo configuration
      file:
        path: /etc/yum.repos.d/jenkins.repo
        state: absent
      ignore_errors: yes

    - name: Remove existing Jenkins GPG key
      command: rpm -e gpg-pubkey-ef5975ca
      ignore_errors: yes

    - name: Download Jenkins package
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins-2.452.1-1.1.noarch.rpm
        dest: /tmp/jenkins.rpm

    - name: Import Jenkins GPG key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key

    - name: Install Jenkins package
      command: rpm -ivh /tmp/jenkins.rpm

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to start up
      wait_for:
        port: 8080
        host: localhost
        delay: 30
        timeout: 300

    - name: Get Jenkins initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password

    - name: Print Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password is: {{ jenkins_initial_password.stdout }}"

  handlers:
    - name: restart jenkins
      systemd:
        name: jenkins
        state: restarted
