apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/database:latest
        ports:
        - containerPort: 3306

